# Generated by Django 2.2 on 2020-01-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191222_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ar_category',
            field=models.CharField(choices=[('S', 'ملابس شبابيه'), ('SW', 'ملابس رياضية'), ('OW', 'ملابس للخروج')], default='شسيب', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='ar_description',
            field=models.TextField(default='سيي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='ar_label',
            field=models.CharField(choices=[('P', 'اولى'), ('S', 'ثانوى'), ('D', 'خطر')], default='شي', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='ar_title',
            field=models.CharField(default='قميص', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=4),
        ),
    ]
