# Generated by Django 2.2 on 2020-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.AddField(
            model_name='address',
            name='customer_name',
            field=models.CharField(default='ww', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='ww@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(default=11111111111111),
            preserve_default=False,
        ),
    ]
