# Generated by Django 2.2 on 2020-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200120_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
