# Generated by Django 2.2 on 2020-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200303_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
